use testing;
#features_credit_0,features_0
#15+158=173维特征！
#features都是补齐过的！
drop table if exists training_merge_2017112;
create table training_merge_2017112
(
select
t3.user_id,
#features_0:15
t1.sex_type,
t1.occupation,
t1.education,
t1.marriage,
t1.person_type, 
t1.sex_occupation,
t1.sex_education,
t1.sex_marriage,
t1.sex_persontype,
t1.occupation_education,
t1.occupation_marriage,
t1.occupation_persontype,
t1.education_marriage,
t1.education_persontype,
t1.marriage_persontype,
#features_credit:158
#1）各项对应均值：（贷前+贷后）/2；—67-15=52维：
#21: features_1
t2.avg_credit_card_numbers,#0.018
t2.avg_mean_credit_limit,#0.057
t2.avg_max_credit_limit,#0.038
t2.avg_min_credit_limit,#0.020
t2.avg_s_1_times,#0.00014
t2.avg_s_1_times_prob,#0.00035
t2.avg_s_0_times,#0.072
t2.avg_s_0_times_prob,#0.0125
t2.avg_mean_cycle_interest,#0.027
t2.avg_max_cycle_interest,#0.027
t2.avg_min_cycle_interest,#0.0018
t2.avg_mean_zuidihuankuan,#0.085
t2.avg_min_zuidihuankuan,#0.063
t2.avg_max_zuidihuankuan,#0.09
t2.avg_mean_moneyreturn_rate,#0.081
t2.avg_mean_lastmoneyreturn,#0.060
t2.avg_min_lastmoneyreturn,#0.017
t2.avg_max_lastmoneyreturn,#0.066
t2.avg_mean_lastmoneyuse,#0.051
t2.avg_min_lastmoneyuse,#0.034
t2.avg_max_lastmoneyuse,#0.061
#18:features_2
t2.avg_mean_consume_numbers,
t2.avg_max_consume_numbers,
t2.avg_min_consume_numbers,
t2.avg_mean_yue,
t2.avg_max_yue,
t2.avg_min_yue,
t2.avg_mean_jine,
t2.avg_max_jine,
t2.avg_min_jine,
t2.avg_bias_jine_yue,
t2.avg_mean_available,
t2.avg_max_available,
t2.avg_min_available,
t2.avg_mean_adjust,
t2.avg_max_adjust,
t2.avg_min_adjust,
t2.avg_consumed_money,
t2.avg_consumed_rate,
#13维！features_3
t2.avg_time_creditUsing,
t2.avg_mean_last_using_back,
t2.avg_rate_consume_lastback,
t2.avg_rate_consume_back,
t2.avg_limit_lastusing,
t2.avg_limit_thisusing,
t2.avg_mean_thisneedback_thisusing,
t2.avg_mean_consume,
t2.avg_rate_consume_cycle,
t2.avg_rate_consumetimes_cycle,
t2.avg_rate_cycle_limit,
t2.avg_rate_consume_limit,
t2.avg_rate_lastback_limit,
#2）各项对应的差：（贷前-贷后）！
#21: features_1
t2.bias_credit_card_numbers,#0.018
t2.bias_mean_credit_limit,#0.057
t2.bias_max_credit_limit,#0.038
t2.bias_min_credit_limit,#0.020
t2.bias_s_1_times,#0.00014
t2.bias_s_1_times_prob,#0.00035
t2.bias_s_0_times,#0.072
t2.bias_s_0_times_prob,#0.0125
t2.bias_mean_cycle_interest,#0.027
t2.bias_max_cycle_interest,#0.027
t2.bias_min_cycle_interest,#0.0018
t2.bias_mean_zuidihuankuan,#0.085
t2.bias_min_zuidihuankuan,#0.063
t2.bias_max_zuidihuankuan,#0.09
t2.bias_mean_moneyreturn_rate,#0.081bias_
t2.bias_mean_lastmoneyreturn,#0.060
t2.bias_min_lastmoneyreturn,#0.017
t2.bias_max_lastmoneyreturn,#0.066
t2.bias_mean_lastmoneyuse,#0.051
t2.bias_min_lastmoneyuse,#0.034
t2.bias_max_lastmoneyuse,#0.061
#18:features_2
t2.bias_mean_consume_numbers,
t2.bias_max_consume_numbers,
t2.bias_min_consume_numbers,
t2.bias_mean_yue,
t2.bias_max_yue,
t2.bias_min_yue,
t2.bias_mean_jine,
t2.bias_max_jine,
t2.bias_min_jine,
t2.bias_bias_jine_yue,
t2.bias_mean_available,
t2.bias_max_available,
t2.bias_min_available,
t2.bias_mean_adjust,
t2.bias_max_adjust,
t2.bias_min_adjust,
t2.bias_consumed_money,
t2.bias_consumed_rate,
#13:features_3
t2.bias_time_creditUsing,
t2.bias_mean_last_using_back,
t2.bias_rate_consume_lastback,
t2.bias_rate_consume_back,
t2.bias_limit_lastusing,
t2.bias_limit_thisusing,
t2.bias_mean_thisneedback_thisusing,
t2.bias_mean_consume,
t2.bias_rate_consume_cycle,
t2.bias_rate_consumetimes_cycle,
t2.bias_rate_cycle_limit,
t2.bias_rate_consume_limit,
t2.bias_rate_lastback_limit,
#3）各项对应的变化率：（差）/均值！52维！
#21: features_1
t2.changeRate_credit_card_numbers,#0.018
t2.changeRate_mean_credit_limit,#0.057
t2.changeRate_max_credit_limit,#0.038
t2.changeRate_min_credit_limit,#0.020
t2.changeRate_s_1_times,#0.00014
t2.changeRate_s_1_times_prob,#0.00035
t2.changeRate_s_0_times,#0.072
t2.changeRate_s_0_times_prob,#0.0125
t2.changeRate_mean_cycle_interest,#0.027
t2.changeRate_max_cycle_interest,#0.027
t2.changeRate_min_cycle_interest,#0.0018
t2.changeRate_mean_zuidihuankuan,#0.085
t2.changeRate_min_zuidihuankuan,#0.063
t2.changeRate_max_zuidihuankuan,#0.09
t2.changeRate_mean_moneyreturn_rate,#0.081
t2.changeRate_mean_lastmoneyreturn,#0.060
t2.changeRate_min_lastmoneyreturn,#0.017
t2.changeRate_max_lastmoneyreturn,#0.066
t2.changeRate_mean_lastmoneyuse,#0.051
t2.changeRate_min_lastmoneyuse,#0.034
t2.changeRate_max_lastmoneyuse,#0.061
#18:features_2
t2.changeRate_mean_consume_numbers,
t2.changeRate_max_consume_numbers,
t2.changeRate_min_consume_numbers,
t2.changeRate_mean_yue,
t2.changeRate_max_yue,
t2.changeRate_min_yue,
t2.changeRate_mean_jine,
t2.changeRate_max_jine,
t2.changeRate_min_jine,
t2.changeRate_bias_jine_yue,
t2.changeRate_mean_available,
t2.changeRate_max_available,
t2.changeRate_min_available,
t2.changeRate_mean_adjust,
t2.changeRate_max_adjust,
t2.changeRate_min_adjust,
t2.changeRate_consumed_money,
t2.changeRate_consumed_rate,
#13:features_3
t2.changeRate_time_creditUsing,
t2.changeRate_mean_last_using_back,
t2.changeRate_rate_consume_lastback,
t2.changeRate_rate_consume_back,
t2.changeRate_limit_lastusing,
t2.changeRate_limit_thisusing,
t2.changeRate_mean_thisneedback_thisusing,
t2.changeRate_mean_consume,
t2.changeRate_rate_consume_cycle,
t2.changeRate_rate_consumetimes_cycle,
t2.changeRate_rate_cycle_limit,
t2.changeRate_rate_consume_limit,
t2.changeRate_rate_lastback_limit,
#单独把时间特征弄两列！
t2.loanBefore_CreditUsingTime,
t2.loanAfter_CreditUsingTime
#lable
#t3.lable
from
features_0 as t1,
features_credit_0 as t2,
userid_predict_final as t3
#overdue_new_final as t3
where 
(t3.user_id=t1.user_id)
and
(t3.user_id=t2.user_id)
#and
#(t1.user_id=t3.user_id)
);